# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'lqb2 spiritual formation (project)'
description: 'this is me following my own journey and sharing it with you'
permalink: pretty
logo: "https://i.imgur.com/QPuQ6LM.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  home: /
  reading: /reading/
  updates: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "following my spiritual formation"
    feature_text: |
      
    feature_image: "https://i.imgur.com/btyODva.jpg"